# A role configures access permissions to clusters, indices, documents or
# fields. Each entry can reference one or more actions groups defined in
# sg_action_groups.yml, as well as single permissions.
#
# Seach Guard ships with a list of built-in roles.
#
# See
#  - https://docs.search-guard.com/latest/roles-permissions
#  - https://git.floragunn.com/search-guard/search-guard/-/blob/master/sgconfig/sg_roles.yml

_sg_meta:
  type: roles
  config_version: 2

## Demo roles
#

# Allows everything, but no changes to searchguard configuration index
sg_all_access:
  reserved: true
  cluster_permissions:
    - UNLIMITED
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - UNLIMITED

# Read all, but no write permissions
sg_readall:
  reserved: true
  cluster_permissions:
    - CLUSTER_COMPOSITE_OPS_RO
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - READ

# Read all and monitor, but no write permissions
sg_readall_and_monitor:
  cluster_permissions:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS_RO
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - READ

# For users which use kibana, access to indices must be granted separately
sg_kibana_user:
  reserved: true
  cluster_permissions:
    - INDICES_MONITOR
    - CLUSTER_COMPOSITE_OPS
  index_permissions:
    - index_patterns:
        - ?kibana
        - ?kibana-6
        - ?kibana_*
      allowed_actions:
        - MANAGE
        - INDEX
        - READ
        - DELETE
    - index_patterns:
        - ?tasks
        - ?management-beats
      allowed_actions:
        - INDICES_ALL
    - index_patterns:
        - '*'
      allowed_actions:
        - indices:data/read/field_caps*
        - indices:data/read/xpack/rollup*
        - indices:admin/mappings/get*
        - indices:admin/get

# For the kibana server
sg_kibana_server:
  reserved: true
  cluster_permissions:
      - CLUSTER_MONITOR
      - CLUSTER_COMPOSITE_OPS
      - cluster:admin/xpack/monitoring*
      - indices:admin/template*
      - indices:data/read/scroll*
  index_permissions:
    - index_patterns:
        - ?kibana
        - ?kibana-6
        - ?kibana_*
        - ?reporting*
        - ?monitoring*
        - ?tasks
        - ?management-beats*
      allowed_actions:
        - INDICES_ALL
    - index_patterns:
        - '*'
      allowed_actions:
        - indices:admin/aliases*

# For logstash and beats
sg_logstash:
  cluster_permissions:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
    - CLUSTER_MANAGE_INDEX_TEMPLATES
    - CLUSTER_MANAGE_ILM
    - CLUSTER_MANAGE_PIPELINES
    - cluster:admin/xpack/monitoring/bulk
  index_permissions:
    - index_patterns:
        - logstash-*
        - '*beat*'
      allowed_actions:
        - CRUD
        - CREATE_INDEX
        - MANAGE
    - index_patterns:
        - '*'
      allowed_actions:
        - indices:admin/aliases/get

# Allows adding and modifying repositories and creating and restoring snapshots
sg_manage_snapshots:
  cluster_permissions:
    - MANAGE_SNAPSHOTS
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - indices:data/write/index
        - indices:admin/create

# Allows each user to access own named index
sg_own_index:
  cluster_permissions:
    - CLUSTER_COMPOSITE_OPS
  index_permissions:
    - index_patterns:
        - '${user_name}'
      allowed_actions:
        - INDICES_ALL

### X-Pack COMPATIBILITY
sg_xp_monitoring:
  reserved: true
  cluster_permissions:
    - cluster:monitor/xpack/info
    - cluster:monitor/main
    - cluster:admin/xpack/monitoring/bulk
  index_permissions:
    - index_patterns:
        - ?monitor*
      allowed_actions:
        - INDICES_ALL

sg_xp_alerting:
  reserved: true
  cluster_permissions:
    - indices:data/read/scroll
    - cluster:admin/xpack/watcher*
    - cluster:monitor/xpack/watcher*
  index_permissions:
    - index_patterns:
        - ?watches*
        - ?watcher-history-*
        - ?triggered_watches
      allowed_actions:
        - INDICES_ALL
    - index_patterns:
        - '*'
      allowed_actions:
        - READ
        - indices:admin/aliases/get

sg_xp_machine_learning:
  reserved: true
  cluster_permissions:
    - cluster:admin/persistent*
    - cluster:internal/xpack/ml*
    - indices:data/read/scroll*
    - cluster:admin/xpack/ml*
    - cluster:monitor/xpack/ml*
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - READ
        - indices:admin/get*
    - index_patterns:
        - ?ml-*
      allowed_actions:
        - '*'
