# Search Guard uses role mappings to determine which Search Guard roles should
# be assigned to the user after authentication. Users and backend roles are
# defined in sg_internal_users.yml.
#
# See
#  - https://docs.search-guard.com/latest/mapping-users-roles
#  - https://git.floragunn.com/search-guard/search-guard/-/blob/master/sgconfig/sg_roles_mapping.yml

_sg_meta:
  type: rolesmapping
  config_version: 2

## Demo roles mappings
#

sg_all_access:
  reserved: true
  backend_roles:
    - admin

sg_logstash:
  backend_roles:
    - logstash

sg_kibana_server:
  reserved: true
  users:
    - kibanaserver

sg_kibana_user:
  backend_roles:
    - kibanauser

sg_readall:
  reserved: true
  backend_roles:
    - readall

sg_manage_snapshots:
  reserved: true
  backend_roles:
    - snapshotrestore

sg_own_index:
  users:
    - '*'
